measurement_point: "s40"
camera_name: "s_cam_near"
objects_file: "/mnt/local_data/providentia/hd_map/NewMap/2021-07-07_1490_Providentia_Plus_Plus_1_6/2021-07-07_1490_Providentia_Plus_Plus_1_6.xodr_objects.yaml"
lane_samples_file: "/mnt/local_data/providentia/hd_map/NewMap/2021-07-07_1490_Providentia_Plus_Plus_1_6/2021-07-07_1490_Providentia_Plus_Plus_1_6.xodr_lane_samples.yaml"
explicit_road_marks_file: "/mnt/local_data/providentia/hd_map/NewMap/2021-07-07_1490_Providentia_Plus_Plus_1_6/2021-07-07_1490_Providentia_Plus_Plus_1_6.xodr_explicit_road_marks.yaml"
pixels_file: "/mnt/local_data/providentia/static_calibration/s40/n/near/frame.bmp_result.yaml"
mapping_file: "/mnt/local_data/providentia/static_calibration/s40/n/near/mapping.yaml"
background_frame: "/mnt/local_data/providentia/static_calibration/s40/n/near/frame.bmp"
output_dir: "/mnt/local_data/providentia/static_calibration/s40/n/near/results"
intrinsics: [ 2788.860717, 2783.312609, 907.839058, 589.071478 ]
ros_tf2_coordinates: true
translation: [ -444.62679384269882, 117.6633265127147, 10.015564539146094 ]
rotation: [ -25.070043672011732, 13.246715975181758, -1.3265076992368805 ]
optimize_intrinsics: False
evaluation_runs: 1000
log_optimization: True
