measurement_point: "s50"
camera_name: "s_cam_far"
objects_file: "/mnt/local_data/providentia/hd_map/NewMap/HiDrive/2021-06-02_1490_Providentia_Plus_Plus_1_4/2021-06-02_1490_Providentia_Plus_Plus_1_4.yaml"
lane_samples_file: "/mnt/local_data/providentia/hd_map/NewMap/HiDrive/2021-06-02_1490_Providentia_Plus_Plus_1_6/2021-06-02_1490_Providentia_Plus_Plus_1_6.xodr_lane_samples.yaml"
explicit_road_marks_file: "/mnt/local_data/providentia/hd_map/NewMap/HiDrive/2021-06-02_1490_Providentia_Plus_Plus_1_6/2021-06-02_1490_Providentia_Plus_Plus_1_6.xodr_explicit_road_marks.yaml"
pixels_file: "/mnt/local_data/providentia/static_calibration/s50/s/far/frame.bmp_result.yaml"
background_frame: "/mnt/local_data/providentia/static_calibration/s50/s/far/frame.bmp"
intrinsics: [ 8878.579697, 8811.724025, 584.217565, 465.520403 ]
optimize_intrinsics: False
evaluation_runs: 10
log_optimization: True
